[package]
name = "a01_add_rapier_bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
bevy_rapier2d = "0.27.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
