[package]
name = "benches_common_3d"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", default-features = false }
avian3d = { git = "https://github.com/Jondolf/avian", default-features = false}
criterion = "0.5"
