[package]
name = "a01_rigid_body"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
avian3d = { git = "https://github.com/Jondolf/avian", branch = "main" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
